### ISSUE TITLE
Long syncs download inconsistent data

### ISSUE THREAD

**Issue by mngan** [peeringdb/django-peeringdb#20]
When performing a full sync, each table will pull from an increasing window of records. So it is possible to pull a record that refers to a parent record that has yet to be synchronized. The solution is to ensure that every table sync's exactly the same window of records by setting the maximum "updated" field. 

[sync_update_diff.txt](https://github.com/peeringdb/django-peeringdb/files/1853784/sync_update_diff.txt)

**Comment by vegu** [comment]
@mngan Thanks a lot for the patch - i agree that this makes sense to add. Have not tested it yet, will see about doing so this week.

**Comment by mngan** [comment]
Ugh. I had a typo. I had update__lte not update**d**_lte

**Comment by vegu** [comment]
Gotcha.

To clarify, it should indeed accept a full ISO8601 format.

So i looked at it and i think we may want to rethink the approach a bit:

I can see here that querying the api with `updated__lte` circumvents use of the api cache as it needs to do a query and pdb is currently not serving cached responses when doing that. Thus making the requests about three times as slow than just passing since=0 (which is the same as not passing since at all, and thus not having to perform any queries). 

While this should work and you're fine to use it as a fix in your local copy, for the general population i instead propose we this check for updated locally, simply ignore any object that's older than the date we set at the beginning of the command. 

It should have the same effect but offload the work to the client instead of the server.

I am currently testing this, and will commit either later today or over the weekend.

**Comment by vegu** [comment]
Also what version of django-peeringdb are you running?

**Comment by vegu** [comment]
So looking at the code some more we actually have a fail safe in place already that should get missing relationships in situations like the one you are describing. Wonder why that's not triggering in your case.

**Comment by mngan** [comment]
I was just using a pip installed version which looks like 0.3.1? I haven't tried the master version from git yet. We were seeing multiple times a week, mainly because we hadn't re-enabled incremental updates. We have a daily job that runs around 12:00UTC to update our local snapshot.

**Comment by vegu** [comment]
looks like the missing object retrieval was fixed in 0.4.0, so could try upgrading to that and see if that fixes your issue.

Don't upgrade to latest if you're running it with the peeringdb client as that currently only supports up to 0.4.0.

**Comment by mngan** [comment]
I see, I had the peeringdb client installed and that was holding back the version of django_peeringdb. I wasn't using the client, so I have removed this which gets me up to the latest version. I'll give this a try and see how things go.

**Comment by mngan** [comment]
0.4.0 seems to address the issues. Thanks
